config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :emissores, except: [:show, :destroy]
  resources :clientes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cliente.rb
# == Schema Information
#
# Table name: clientes
#
#  id                  :integer          not null, primary key
#  tipo_de_pessoa_id   :integer          not null
#  numero_do_documento :string           not null
#  inscricao_estadual  :string
#  inscricao_municipal :string
#  razao_social        :string           not null
#  nome_fantasia       :string
#  cep                 :string           not null
#  endereco            :string           not null
#  numero              :string
#  complemento         :string
#  bairro              :string           not null
#  pais_id             :integer          not null
#  uf_id               :integer          not null
#  municipio_id        :integer          not null
#  user_id             :integer          not null
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Cliente < ApplicationRecord
  belongs_to :tipo_de_pessoa
  belongs_to :municipio
  belongs_to :user
  belongs_to :uf
  belongs_to :pais

  delegate :codigo, to: :tipo_de_pessoa, prefix: true, allow_nil: true
  delegate :nome_por_extenso, to: :tipo_de_pessoa, prefix: true, allow_nil: true
  delegate :nome, to: :uf, prefix: true, allow_nil: true

  validates_presence_of :tipo_de_pessoa_id, :numero_do_documento,
    :razao_social, :cep, :endereco, :bairro, :pais_id, :uf_id, :municipio_id,
    :user_id
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_cliente, only: [:edit, :update, :destroy]

  def index
    @clientes = current_user.clientes.decorate
  end

  def new
    @cliente = current_user.clientes.new
  end

  def create
    @cliente = current_user.clientes.new(cliente_params)
    if @cliente.save
      flash[:notice] = 'Cliente cadastrado com sucesso'
      redirect_to clientes_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @cliente.update(cliente_params)
      flash[:notice] = 'Cliente atualizado com sucesso'
      redirect_to clientes_path
    else
      render :edit
    end
  end

  def destroy
    @cliente.destroy
    flash[:notice] = 'Cliente deletado com sucesso'
    redirect_to clientes_path
  end

  private

  def find_cliente
    @cliente = current_user.clientes.find(params[:id])
  end

  def cliente_params
    params.require(:cliente).permit(
      :tipo_de_pessoa_id, :numero_do_documento,
      :inscricao_estadual, :inscricao_municipal,
      :razao_social, :cep, :endereco, :numero,
      :complemento, :bairro, :pais_id, :uf_id,
      :municipio_id
    )
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= simple_form_for(@cliente) do |f| %>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Clientes
        <small>Formulário</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/clientes">Clientes</a></li>
        <li class="active">Formulário</li>
      </ol>
    </section>

    <section class="content">
      <div class="row">
        <div class="col-md-12">
      	  <%= render 'informacoes_de_cadastro', f: f %>
          <%= render 'informacoes_de_endereco', f: f %>
        </div>
      </div>
      <%= render 'submit', f: f %>
    </section>
  </div>
<% end %>

app/views/clientes/_informacoes_de_cadastro.html.erb
<div class="box box-default">
  <div class="box-header with-border">
    <h3 class="box-title">Informações cadastrais</h3>
  </div>

  <div class="box-body">
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.input :tipo_de_pessoa_id, collection: TipoDePessoa.all, label_method: :nome_por_extenso, value_method: :id %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.input :numero_do_documento %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <%= f.input :razao_social %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.input :inscricao_estadual %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.input :inscricao_municipal %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/clientes/_informacoes_de_endereco.html.erb
<div class="box box-default">
  <div class="box-header with-border">
    <h3 class="box-title">Endereço</h3>
  </div>

  <div class="box-body">
    <div class="row">
      <div class="col-md-3">
        <div class="form-group">
          <%= f.input :cep %>
        </div>
      </div>
      <div class="col-md-9">
        <div class="form-group">
          <%= f.input :endereco %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <div class="form-group">
          <%= f.input :numero %>
        </div>
      </div>
      <div class="col-md-3">
        <div class="form-group">
          <%= f.input :complemento %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= f.input :bairro %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-5">
        <div class="form-group">
          <%= f.input :pais_id, collection: Pais.all, label_method: :nome, value_method: :id %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.input :uf_id, collection: Uf.all, label_method: :nome, value_method: :id %>
        </div>
      </div>
      <div class="col-md-5">
        <div class="form-group">
          <%= f.input :municipio_id, collection: Municipio.all, label_method: :nome, value_method: :id %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/clientes/_submit.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="btn-group pull-right">
      <%= f.submit 'Salvar', class: 'btn btn-primary' %>
      <%= link_to 'Voltar', clientes_path, class: 'btn btn-default' %>
    </div>
  </div>
</div>

app/views/clientes/edit.html.erb
<%= render 'form' %>

app/views/clientes/index.html.erb
<div class="content-wrapper">
  <section class="content-header">
    <h1>
      Clientes
      <small>lista</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Clientes</li>
    </ol>
  </section>

  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">Clientes</h3>
          </div>
          <div class="box-body">
            <table class="table table-bordered table-hover">
              <thead>
                <tr>
                  <th width="150px">Tipo de pessoa</th>
                  <th width="150px">CNPJ/CPF</th>
                  <th>Razão social</th>
                  <th width="50px">UF</th>
                  <th width="100px"><%= link_to 'Cadastrar', new_cliente_path, class: 'btn btn-primary btn-flat' %></th>
                </tr>
              </thead>
              <tbody>
              <% @clientes.each do |cliente| %>
                <tr>
                  <td><%= cliente.tipo_de_pessoa_nome_por_extenso %></td>
                  <td><%= cliente.numero_do_documento %></td>
                  <td><%= cliente.razao_social %></td>
                  <td><%= cliente.uf_nome %></td>
                  <td>
                    <%= link_to('Editar', edit_cliente_path(cliente)) %> /
                    <%= link_to 'Deletar', cliente, method: :delete, data: {
                        confirm: "Tem certeza que deseja deletar o cliente #{cliente.razao_social}" } %>
                  </td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>